// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: automate_orders.proto

package com.grpc.orderService;

public final class AutomateOrdersImpl {
  private AutomateOrdersImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockQuoteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockQuoteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockQuoteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockQuoteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filterPriceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filterPriceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filterPriceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_filterPriceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025automate_orders.proto\".\n\014orderRequest\022" +
      "\014\n\004item\030\001 \001(\t\022\020\n\010quantity\030\002 \001(\005\" \n\rorder" +
      "Response\022\017\n\007message\030\001 \001(\t\"[\n\007product\022\020\n\010" +
      "stock_id\030\001 \001(\005\022\014\n\004cost\030\002 \001(\002\022\024\n\014product_" +
      "name\030\003 \001(\t\022\032\n\022quantity_available\030\004 \001(\005\"4" +
      "\n\022StockQuoteResponse\022\017\n\007message\030\001 \001(\t\022\r\n" +
      "\005price\030\003 \001(\002\"@\n\021StockQuoteRequest\022\031\n\007pro" +
      "duct\030\001 \001(\0132\010.product\022\020\n\010quantity\030\002 \001(\005\"&" +
      "\n\022filterPriceRequest\022\020\n\010maxPrice\030\001 \001(\005\"0" +
      "\n\023filterPriceResponse\022\031\n\007product\030\001 \001(\0132\010" +
      ".product2\275\001\n\014orderService\022.\n\013createOrder" +
      "\022\r.orderRequest\032\016.orderResponse\"\000\022?\n\020str" +
      "eamStockQuote\022\022.StockQuoteRequest\032\023.Stoc" +
      "kQuoteResponse\"\000(\001\022<\n\013filterPrice\022\023.filt" +
      "erPriceRequest\032\024.filterPriceResponse\"\0000\001" +
      "B-\n\025com.grpc.orderServiceB\022AutomateOrder" +
      "sImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_orderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_orderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orderRequest_descriptor,
        new java.lang.String[] { "Item", "Quantity", });
    internal_static_orderResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_orderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orderResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_product_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_descriptor,
        new java.lang.String[] { "StockId", "Cost", "ProductName", "QuantityAvailable", });
    internal_static_StockQuoteResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_StockQuoteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockQuoteResponse_descriptor,
        new java.lang.String[] { "Message", "Price", });
    internal_static_StockQuoteRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_StockQuoteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockQuoteRequest_descriptor,
        new java.lang.String[] { "Product", "Quantity", });
    internal_static_filterPriceRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_filterPriceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filterPriceRequest_descriptor,
        new java.lang.String[] { "MaxPrice", });
    internal_static_filterPriceResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_filterPriceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_filterPriceResponse_descriptor,
        new java.lang.String[] { "Product", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
