// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: automate_orders.proto

package com.grpc.orderService;

public final class AutomateOrdersImpl {
  private AutomateOrdersImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockQuoteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockQuoteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockQuoteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockQuoteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Cart_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Cart_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025automate_orders.proto\".\n\014orderRequest\022" +
      "\014\n\004item\030\001 \001(\t\022\020\n\010quantity\030\002 \001(\005\" \n\rorder" +
      "Response\022\017\n\007message\030\001 \001(\t\"*\n\007product\022\r\n\005" +
      "title\030\001 \001(\t\022\020\n\010quantity\030\002 \001(\005\"P\n\022StockQu" +
      "oteResponse\022\017\n\007message\030\001 \001(\t\022\032\n\010products" +
      "\030\002 \003(\0132\010.product\022\r\n\005price\030\003 \001(\005\"A\n\021Stock" +
      "QuoteRequest\022\032\n\010products\030\001 \003(\0132\010.product" +
      "\022\020\n\010quantity\030\002 \001(\005\"B\n\004Cart\022\017\n\007message\030\001 " +
      "\001(\t\022\r\n\005total\030\002 \001(\005\022\032\n\010products\030\003 \003(\0132\010.p" +
      "roduct2\246\001\n\014orderService\022.\n\013createOrder\022\r" +
      ".orderRequest\032\016.orderResponse\"\000\022?\n\020strea" +
      "mStockQuote\022\022.StockQuoteRequest\032\023.StockQ" +
      "uoteResponse\"\000(\001\022%\n\016totalCartValue\022\010.pro" +
      "duct\032\005.Cart\"\000(\001B-\n\025com.grpc.orderService" +
      "B\022AutomateOrdersImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_orderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_orderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orderRequest_descriptor,
        new java.lang.String[] { "Item", "Quantity", });
    internal_static_orderResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_orderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orderResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_product_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_descriptor,
        new java.lang.String[] { "Title", "Quantity", });
    internal_static_StockQuoteResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_StockQuoteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockQuoteResponse_descriptor,
        new java.lang.String[] { "Message", "Products", "Price", });
    internal_static_StockQuoteRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_StockQuoteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockQuoteRequest_descriptor,
        new java.lang.String[] { "Products", "Quantity", });
    internal_static_Cart_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Cart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Cart_descriptor,
        new java.lang.String[] { "Message", "Total", "Products", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
