// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: automate_orders.proto

package com.grpc.orderService;

public interface FilterPriceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FilterPriceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string product = 1;</code>
   */
  java.lang.String getProduct();
  /**
   * <code>string product = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductBytes();
}
