// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: automate_orders.proto

package com.grpc.orderService;

public interface FilterPriceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FilterPriceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 maxPrice = 1;</code>
   */
  int getMaxPrice();
}
