// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: automate_orders.proto

package com.grpc.orderService;

public interface orderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string item = 1;</code>
   */
  java.lang.String getItem();
  /**
   * <code>string item = 1;</code>
   */
  com.google.protobuf.ByteString
      getItemBytes();

  /**
   * <code>int32 quantity = 2;</code>
   */
  int getQuantity();
}
