// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: automate_orders.proto

package com.grpc.orderService;

public interface productOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 stock_id = 1;</code>
   */
  int getStockId();

  /**
   * <code>float cost = 2;</code>
   */
  float getCost();

  /**
   * <code>string product_name = 3;</code>
   */
  java.lang.String getProductName();
  /**
   * <code>string product_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>int32 quantity_available = 4;</code>
   */
  int getQuantityAvailable();
}
