// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: automate_orders.proto

package com.grpc.orderService;

public interface reportRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:reportRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string date_one = 1;</code>
   */
  java.lang.String getDateOne();
  /**
   * <code>string date_one = 1;</code>
   */
  com.google.protobuf.ByteString
      getDateOneBytes();

  /**
   * <code>string date_two = 2;</code>
   */
  java.lang.String getDateTwo();
  /**
   * <code>string date_two = 2;</code>
   */
  com.google.protobuf.ByteString
      getDateTwoBytes();
}
