// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: automate_orders.proto

package com.grpc.orderService;

public interface StockQuoteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StockQuoteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .product products = 1;</code>
   */
  java.util.List<com.grpc.orderService.product> 
      getProductsList();
  /**
   * <code>repeated .product products = 1;</code>
   */
  com.grpc.orderService.product getProducts(int index);
  /**
   * <code>repeated .product products = 1;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .product products = 1;</code>
   */
  java.util.List<? extends com.grpc.orderService.productOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .product products = 1;</code>
   */
  com.grpc.orderService.productOrBuilder getProductsOrBuilder(
      int index);

  /**
   * <code>int32 quantity = 2;</code>
   */
  int getQuantity();
}
