// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: automate_orders.proto

package com.grpc.orderService;

public interface StockQuoteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StockQuoteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated .product products = 2;</code>
   */
  java.util.List<com.grpc.orderService.product> 
      getProductsList();
  /**
   * <code>repeated .product products = 2;</code>
   */
  com.grpc.orderService.product getProducts(int index);
  /**
   * <code>repeated .product products = 2;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .product products = 2;</code>
   */
  java.util.List<? extends com.grpc.orderService.productOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .product products = 2;</code>
   */
  com.grpc.orderService.productOrBuilder getProductsOrBuilder(
      int index);

  /**
   * <code>int32 price = 3;</code>
   */
  int getPrice();
}
