// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory_management.proto

package com.grpc.stockCheckerService;

public interface addStockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:addStockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string productName = 1;</code>
   */
  java.lang.String getProductName();
  /**
   * <code>string productName = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>float cost = 2;</code>
   */
  float getCost();

  /**
   * <code>int32 quantity_available = 3;</code>
   */
  int getQuantityAvailable();
}
