// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory_management.proto

package com.grpc.stockCheckerService;

public final class InventoryManagement {
  private InventoryManagement() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lowStockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lowStockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lowStockResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lowStockResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032inventory_management.proto\032\025automate_o" +
      "rders.proto\"#\n\017lowStockRequest\022\020\n\010quanti" +
      "ty\030\001 \001(\005\"?\n\020lowStockResponse\022\017\n\007message\030" +
      "\001 \001(\t\022\032\n\010products\030\002 \003(\0132\010.product2\250\001\n\027in" +
      "ventoryCheckerService\022*\n\022addProductsToSt" +
      "ock\022\010.product\032\010.product\"\000\022)\n\021updateProdu" +
      "ctInfo\022\010.product\032\010.product\"\000\0226\n\rcheckLow" +
      "Stock\022\020.lowStockRequest\032\021.lowStockRespon" +
      "se\"\000B \n\034com.grpc.stockCheckerServiceP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.grpc.orderService.AutomateOrdersImpl.getDescriptor(),
        }, assigner);
    internal_static_lowStockRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lowStockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lowStockRequest_descriptor,
        new java.lang.String[] { "Quantity", });
    internal_static_lowStockResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lowStockResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lowStockResponse_descriptor,
        new java.lang.String[] { "Message", "Products", });
    com.grpc.orderService.AutomateOrdersImpl.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
