// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory_management.proto

package com.grpc.stockCheckerService;

public interface lowStockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lowStockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 quantity = 1;</code>
   */
  int getQuantity();
}
