// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: update_warehouse_service.proto

package com.grpc.warehouseService;

public interface lastOrdersResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lastOrdersResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string products = 1;</code>
   */
  java.lang.String getProducts();
  /**
   * <code>string products = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductsBytes();
}
