// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: update_warehouse_service.proto

package com.grpc.warehouseService;

public interface lastOrdersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lastOrdersRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 amountOfOrdersToSearch = 1;</code>
   */
  int getAmountOfOrdersToSearch();
}
