// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: update_warehouse_service.proto

package com.grpc.warehouseService;

public interface lastOrdersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lastOrdersRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.product product = 1;</code>
   */
  boolean hasProduct();
  /**
   * <code>.product product = 1;</code>
   */
  com.grpc.orderService.product getProduct();
  /**
   * <code>.product product = 1;</code>
   */
  com.grpc.orderService.productOrBuilder getProductOrBuilder();
}
