// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: update_warehouse_service.proto

package com.grpc.warehouseService;

public interface orderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string orderNumber = 1;</code>
   */
  java.lang.String getOrderNumber();
  /**
   * <code>string orderNumber = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrderNumberBytes();
}
