// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: update_warehouse_service.proto

package com.grpc.warehouseService;

public interface orderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string order = 1;</code>
   */
  java.lang.String getOrder();
  /**
   * <code>string order = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrderBytes();
}
