// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: update_warehouse_service.proto

package com.grpc.warehouseService;

public interface shippingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:shippingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string address = 2;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 2;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string country = 3;</code>
   */
  java.lang.String getCountry();
  /**
   * <code>string country = 3;</code>
   */
  com.google.protobuf.ByteString
      getCountryBytes();
}
